name: CLi Dependencies and Login
description: Download CLi and log into Salesforce DEV hub



runs:
  using: 'composite'
  steps:
    - name: Install Salesforce Dependency
      run: |
                echo "Salesforce CLI installation"
                npm install -g @salesforce/cli --global
                sf --version
      shell: bash
            #- name: Log into Salesforce
