name: CLi Dependencies and Login
description: Download CLi and log into Salesforce DEV hub

inputs:
  cli-version:
    description: 'Call the version'
    required: false
    default: 'Do not Check'



runs:
  using: 'composite'
  steps:
    - name: Install Salesforce Dependency
      run: |
                echo "Salesforce CLI installation"
                npm install -g @salesforce/cli --global
      shell: bash
    - name: Check verion of Salesforce
      if: inputs.cli-version == '--version' 
      run: sf --version
      shell: bash

