name: Salesforce-Deployment
description: Creating salesforce org

on: 
    push:
        branches: 
            - main


jobs: 
    create-scratchOrg:
       # environment: PROD
        env:

            secret-key: ${{ secrets.JWT_SECRET_KEY }}
            consumer-key: ${{ secrets.CONSUMER_KEY }}
            devhub: ${{ secrets.DEVHUB_USERNAME }}
        runs-on: ubuntu-latest
        steps:
            - name: Print out Salesforce
              run: echo "Salesforce Scratch Org"
            - name: Check out Repo
              uses: actions/checkout@v4
            - name: Install Salesforce Dependency
              run: |
                echo "Salesforce CLI installation"
                npm install -g @salesforce/cli --global
                sf --version
                echo "$env.consumer-key"
            #- name: Log into Salesforce
            - run: echo "${{ secrets.SECRET_JWT }}" >> secret.key 
            - run: sf org login jwt --username=${{ secrets.SALESFORCE_USERNAME }}   --jwt-key-file=secret.key  --client-id=${{ secrets.REPO_CONSUMER_SECRET }} --set-default-dev-hub

