name: Salesforce-Deployment
description: Creating salesforce org

on: 
    push:
        branches: 
            - main


jobs: 
    create-scratchOrg:
        environment: PROD
        env:

            secret-key: echo "${{ secrets.JWT_SECRET_KEY }}" >> secret.key
            consumer-key: ${{ secrets.CONSUMER_KEY }}
            devhub: ${{ secrets.DEVHUB_USERNAME }}
        runs-on: ubuntu-latest
        steps:
            - name: Print out Salesforce
              run: echo "Salesforce Scratch Org"
            - name: Check out Repo
              uses: actions/checkout@v4
            - name: Install Salesforce Dependency
              run: |
                echo "Salesforce CLI installation"
                npm install -g @salesforce/cli --global
                sf --version
                echo "$env.consumer-key"
            - name: Log into Salesforce
              run: sf force:auth:jwt:grant --username dubemkutility@gmail.com --jwt-key-file D:\Salesforce\openssl\bin\server.key --client-id 3MVG9YFqzc_KnL.zOgPJ7SzigGxtj.edcfdwD1fawCtF7cJ_r_3XIvD_W5hhpMb574pFUK46qdJKlvYgESGKy --alias dubemk --set-default --instance-url https://login.salesforce.com

