name: Salesforce
description: Creating salesforce org

on: 
    push:
        branches: 
            - main

jobs: 
    create-scratchOrg:
        runs-on: ubuntu-latest
        steps:
            - name: Print out Salesforce
              run: echo "Salesforce Scratch Org"

