name: Salesforce-Deployment
description: Creating salesforce org

on: 
    push:
        branches: 
            - main

env:
                consumer-key: ${{ secrets.CONSUMER_KEY }}
                devhub: ${{ secrets.DEVHUB_USERNAME }}
        

jobs: 
    create-scratchOrg:
        environment: PROD

        runs-on: ubuntu-latest
        steps:
            - name: Print out Salesforce
              run: echo "Salesforce Scratch Org"
            - name: Check out Repo
              uses: actions/checkout@v4
            - name: Download CLi and log in
              uses: ./.github/actions
              with:
                cli-version: 'version'
            - run: echo "${{ secrets.SECRET_JWT }}" >> secret.key 
            - run: sf org login jwt --username=${{ env.devhub }}   --jwt-key-file=secret.key  --client-id=${{ env.consumer-key }} --alias dubemk

            - name: Generate files
              run: |
                
                mkdir -p salesforece-ouput
                
                echo "The File below is for account dubemkutility@gmail.com" >> salesforece-ouput/greetings.txt
                sf org list >> salesforece-ouput/Org-list.txt
            
            - name: Upload Output
              uses: actions/upload-artifact@v4
              with: 
                name: my-sf-query-artifact
                path: salesforece-ouput/Org-list.txt
            - name: Upload Output for Name
              uses: actions/upload-artifact@v4
              with: 
                  name: my-greeting-artifact
                  path: salesforece-ouput/greetings.txt