name: Salesforce-Deployment
description: Creating salesforce org

on: 
    push:
        branches: 
            - main

env:
        consumer-key: ${{ secrets.CONSUMER_KEY }}
        devhub: ${{ secrets.DEVHUB_USERNAME }}


jobs: 
    create-scratchOrg:
        environment: PROD

        runs-on: ubuntu-latest
        steps:
            - name: Print out Salesforce
              run: echo "Salesforce Scratch Org"
            - name: Check out Repo
              uses: actions/checkout@v4
            - name: Download CLi and log in
              uses: ./.github/actions/action.yml
            - run: echo "$custom_action=custom_action_called"